version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: { interval: weekly }
    groups:
      cargo: { patterns: ["*"] }
  - package-ecosystem: npm
    directory: /wasm-pkg
    schedule: { interval: weekly }
    groups:
      npm: { patterns: ["*"] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: monthly }
  - package-ecosystem: docker-compose
    directory: /
    schedule: { interval: monthly }
