//! Safe Rust wrapper over CoolProp.
//!
//! This layer exposes a small, product-friendly API on top of the curated
//! fluid catalog generated by `coolprop-sys`.

use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_long};

pub use coolprop_sys::catalog::{self, FluidData, Variant};

/// A working state for one curated fluid.
#[derive(Debug)]
pub struct Fluid {
    variant: Variant,
}

impl Fluid {
    /// Resolves a fluid by name, accepting human-friendly strings such as
    /// `"water"`, `"Water"`, `"n-propane"`, or `"R1233zd(E)"`.
    pub fn from_name(name: &str) -> Result<Self, String> {
        let variant = Variant::from_name(name)
            .ok_or_else(|| format!("unknown fluid: {name}"))?;
        Ok(Self { variant })
    }

    pub fn variant(&self) -> Variant {
        self.variant
    }

    pub fn name(&self) -> &'static str {
        self.variant.name()
    }

    pub fn data(&self) -> &'static FluidData {
        self.variant.data()
    }

    /// Opens a new HEOS `AbstractState` for this fluid.
    pub fn state(&self) -> Result<State, String> {
        State::new(self.variant)
    }
}

/// Thin wrapper around CoolProp's `AbstractState` handle.
#[derive(Debug)]
pub struct State {
    handle: c_long,
}

impl State {
    fn new(variant: Variant) -> Result<Self, String> {
        let backend = CString::new("HEOS").unwrap();
        let fluid = CString::new(variant.name()).unwrap();
        let mut err: c_long = 0;
        let mut buf = [0 as c_char; 1024];

        let handle = unsafe {
            coolprop_sys::AbstractState_factory(
                backend.as_ptr(),
                fluid.as_ptr(),
                &mut err,
                buf.as_mut_ptr(),
                1024,
            )
        };

        if err == 0 {
            Ok(Self { handle })
        } else {
            let msg = unsafe { CStr::from_ptr(buf.as_ptr()) }
                .to_string_lossy()
                .into_owned();
            Err(msg)
        }
    }

    pub fn temperature(&self) -> f64 {
        self.output("T")
    }

    pub fn pressure(&self) -> f64 {
        self.output("P")
    }

    pub fn density(&self) -> f64 {
        self.output("D")
    }

    pub fn output(&self, param: &str) -> f64 {
        let param_name = CString::new(param).unwrap();
        let mut err: c_long = 0;
        let mut buf = [0 as c_char; 1024];
        let idx = unsafe { coolprop_sys::get_param_index(param_name.as_ptr()) };
        let value = unsafe {
            coolprop_sys::AbstractState_keyed_output(
                self.handle,
                idx,
                &mut err,
                buf.as_mut_ptr(),
                1024,
            )
        };
        if err != 0 {
            panic!("parameter lookup failed for {param}: {}", unsafe {
                CStr::from_ptr(buf.as_ptr())
                    .to_string_lossy()
            });
        }
        value
    }
}

impl Drop for State {
    fn drop(&mut self) {
        let mut err: c_long = 0;
        let mut buf = [0 as c_char; 1024];
        unsafe {
            coolprop_sys::AbstractState_free(
                self.handle,
                &mut err,
                buf.as_mut_ptr(),
                1024,
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fluid_name_lookup_is_case_insensitive() {
        let fluid = Fluid::from_name("water").expect("water should resolve");
        assert_eq!(fluid.name(), "Water");
    }
}
