/**
 * Browser tests (headless Chromium, see vitest.config.ts). The module loads
 * through the default factory, exactly as a bundler consumer would, so this
 * also checks that the .wasm resolves without manual `locateFile` wiring.
 *
 * Requires dist/: run `docker compose run --rm build-npm` first.
 */
import { beforeAll, describe, expect, it } from "vitest";

// @ts-expect-error: generated by `docker compose run --rm build-npm`, untyped.
import createCoolPropModule from "../dist/coolprop.js";
import {
  CoolPropError,
  loadCoolProp,
  type CoolProp,
  type CoolPropModule,
} from "../src/index.js";
import {
  INPUT_PAIRS,
  type InputName,
  type Phase,
  type PropertyName,
} from "../src/types.js";

/**
 * Every member of each TS union, listed once. `satisfies` rejects unknown
 * names; the `Exhaustive` checks reject missing ones. The schema tests below
 * then compare these against what the module reports at runtime.
 */
const INPUT_NAMES = [
  "pressure",
  "temperature",
  "density",
  "enthalpy",
  "entropy",
  "internal_energy",
  "quality",
] as const satisfies readonly InputName[];
const PHASES = [
  "liquid",
  "supercritical",
  "supercritical_gas",
  "supercritical_liquid",
  "critical_point",
  "gas",
  "two_phase",
] as const satisfies readonly Phase[];
const PROPERTY_NAMES = [
  "pressure",
  "temperature",
  "density",
  "enthalpy",
  "entropy",
  "internal_energy",
  "quality",
  "cp",
  "cv",
  "viscosity",
  "conductivity",
  "prandtl",
  "gibbs",
  "compressibility",
  "speed_of_sound",
] as const satisfies readonly PropertyName[];
type Exhaustive<All, Listed> = [Exclude<All, Listed>] extends [never] ? true : never;
const exhaustive: [
  Exhaustive<InputName, (typeof INPUT_NAMES)[number]>,
  Exhaustive<Phase, (typeof PHASES)[number]>,
  Exhaustive<PropertyName, (typeof PROPERTY_NAMES)[number]>,
] = [true, true, true];
void exhaustive;

let cp: CoolProp;

beforeAll(async () => {
  cp = await loadCoolProp();
});

describe("module", () => {
  it("reports the CoolProp version", () => {
    expect(cp.version()).toMatch(/^8\./);
  });

  it("lists the curated catalog with aliases", () => {
    const water = cp.catalog().find((f) => f.name === "Water");
    expect(water?.aliases).toContain("H2O");
    expect(water?.molar_mass).toBeCloseTo(0.018015268, 9);
  });
});

describe("schema", () => {
  it("lists exactly the inputs, phases and properties in the TS types", () => {
    expect(cp.inputs().map((i) => i.name)).toEqual(INPUT_NAMES);
    expect(cp.phases().map((p) => p.name)).toEqual(PHASES);
    expect(cp.properties().map((p) => p.name)).toEqual(PROPERTY_NAMES);
  });

  it("lists exactly the pairs StateInputs accepts", () => {
    expect(cp.pairs()).toEqual(INPUT_PAIRS);
  });

  it("describes units, bounds and nullability", () => {
    const quality = cp.inputs().find((i) => i.name === "quality")!;
    expect([quality.min, quality.max]).toEqual([0, 1]);
    const viscosity = cp.properties().find((p) => p.name === "viscosity")!;
    expect(viscosity).toMatchObject({ unit: "Pa·s", nullable: true, category: "transport" });
  });

  it("matches the keys of a solved state", () => {
    const s = cp.fluid("Water").state({ pressure: 101325, temperature: 298.15 });
    const keys = Object.keys(s).filter((k) => k !== "phase");
    expect(keys.sort()).toEqual([...PROPERTY_NAMES].sort());
  });
});

describe("fluid", () => {
  it("opens by alias and exposes data and the EOS critical point", () => {
    const water = cp.fluid("H2O");
    expect(water.name).toBe("Water");
    expect(water.critical.temperature).toBeCloseTo(647.096, 3);
    expect(water.data.t_triple).toBeCloseTo(273.16, 6);
  });

  it("rejects unknown fluids", () => {
    expect(() => cp.fluid("Unobtainium")).toThrowError(
      expect.objectContaining({ name: "CoolPropError", kind: "unknown_fluid" }),
    );
  });
});

describe("state", () => {
  it("solves a liquid from pressure and temperature", () => {
    const s = cp.fluid("Water").state({ pressure: 101325, temperature: 298.15 });
    expect(s.phase).toBe("liquid");
    expect(s.quality).toBeNull();
    expect(s.enthalpy).toBeCloseTo(104920.1, 0);
    expect(s.cp).toBeGreaterThan(4000);
  });

  it("round-trips through another input pair", () => {
    const water = cp.fluid("Water");
    const a = water.state({ pressure: 101325, quality: 0.5 });
    const b = water.state({ enthalpy: a.enthalpy, entropy: a.entropy });
    expect(b.pressure).toBeCloseTo(101325, 0);
    expect(b.quality).toBeCloseTo(0.5, 6);
  });

  it("classifies errors", () => {
    const water = cp.fluid("Water");
    const kindOf = (fn: () => unknown) => {
      try {
        fn();
      } catch (e) {
        return (e as CoolPropError).kind;
      }
      return "no error";
    };
    expect(kindOf(() => water.state({ pressure: 101325, temperature: -10 }))).toBe("coolprop");
    // Bypass the type check to reach the runtime validation.
    expect(kindOf(() => water.state({ pressure: 1 } as never))).toBe("invalid_input");
  });

  it("solves batches point by point", () => {
    const [liquid, bad, vapor] = cp.fluid("Water").states([
      { pressure: 101325, quality: 0 },
      { pressure: 101325, temperature: -10 },
      { pressure: 101325, quality: 1 },
    ]);
    expect((liquid as { quality: number }).quality).toBe(0);
    expect(bad).toBeInstanceOf(CoolPropError);
    expect((bad as CoolPropError).kind).toBe("coolprop");
    expect((vapor as { quality: number }).quality).toBe(1);
  });

  it("does not leak module memory across many calls", async () => {
    // A dedicated instance whose Emscripten module we can inspect.
    let module: CoolPropModule & { HEAPU8: Uint8Array };
    const own = await loadCoolProp({
      moduleFactory: async (opts) => (module = await createCoolPropModule(opts)),
    });
    const water = own.fluid("Water");
    const call = (i: number) => water.state({ pressure: 101325, temperature: 280 + (i % 50) });
    for (let i = 0; i < 100; i++) call(i); // warm up the allocator
    const before = module!.HEAPU8.buffer.byteLength;
    // Each response is ~0.5 kB of module memory. If any leaked, 50k calls
    // (~24 MB, more than the whole initial ~18 MB heap) would force it to grow.
    for (let i = 0; i < 50000; i++) call(i);
    expect(module!.HEAPU8.buffer.byteLength).toBe(before);
  });
});

describe("web worker", () => {
  it("loads and solves inside a module worker", async () => {
    const worker = new Worker(new URL("./worker.ts", import.meta.url), { type: "module" });
    const result = await new Promise<{ enthalpy?: number; error?: string }>((resolve) => {
      worker.onmessage = (e) => resolve(e.data);
      worker.onerror = (e) => resolve({ error: e.message });
      worker.postMessage(null);
    });
    worker.terminate();
    expect(result.error).toBeUndefined();
    expect(result.enthalpy).toBeCloseTo(104920.1, 0);
  });
});

/** Compile-time only: never called. `tsc --noEmit` fails if any line type-checks. */
export function typeChecks(cp: CoolProp) {
  const water = cp.fluid("Water");
  // @ts-expect-error: one input is not enough.
  water.state({ pressure: 101325 });
  // @ts-expect-error: three inputs are too many.
  water.state({ pressure: 101325, temperature: 300, density: 1 });
  // @ts-expect-error: (quality, internal_energy) is not a supported pair.
  water.state({ quality: 0.5, internal_energy: 2e5 });
  // @ts-expect-error: short names are not part of the contract.
  water.state({ P: 101325, T: 300 });
}
