/**
 * Browser tests (headless Chromium, see vitest.config.ts). The module loads
 * through the default factory, exactly as a bundler consumer would, so this
 * also checks that the .wasm resolves without manual `locateFile` wiring.
 *
 * Requires dist/: run `docker compose run --rm build-npm` first.
 */
import { beforeAll, describe, expect, it } from "vitest";

// @ts-expect-error: generated by `docker compose run --rm build-npm`, untyped.
import createCoolPropModule from "../dist/coolprop.js";
import {
  CoolPropError,
  loadCoolProp,
  type CoolProp,
  type CoolPropModule,
} from "../src/index.js";
import {
  INPUT_PAIRS,
  type InputName,
  type Phase,
  type PlotProperty,
  type PropertyName,
} from "../src/types.js";

/**
 * Every member of each TS union, listed once. `satisfies` rejects unknown
 * names; the `Exhaustive` checks reject missing ones. The schema tests below
 * then compare these against what the module reports at runtime.
 */
const INPUT_NAMES = [
  "pressure",
  "temperature",
  "density",
  "enthalpy",
  "entropy",
  "internal_energy",
  "quality",
] as const satisfies readonly InputName[];
const PHASES = [
  "liquid",
  "supercritical",
  "supercritical_gas",
  "supercritical_liquid",
  "critical_point",
  "gas",
  "two_phase",
] as const satisfies readonly Phase[];
const PROPERTY_NAMES = [
  "pressure",
  "temperature",
  "density",
  "enthalpy",
  "entropy",
  "internal_energy",
  "quality",
  "cp",
  "cv",
  "viscosity",
  "conductivity",
  "prandtl",
  "gibbs",
  "compressibility",
  "speed_of_sound",
] as const satisfies readonly PropertyName[];
const PLOT_PROPERTIES = [
  "pressure",
  "temperature",
  "density",
  "specific_volume",
  "enthalpy",
  "entropy",
  "internal_energy",
] as const satisfies readonly PlotProperty[];
type Exhaustive<All, Listed> = [Exclude<All, Listed>] extends [never] ? true : never;
const exhaustive: [
  Exhaustive<InputName, (typeof INPUT_NAMES)[number]>,
  Exhaustive<Phase, (typeof PHASES)[number]>,
  Exhaustive<PropertyName, (typeof PROPERTY_NAMES)[number]>,
  Exhaustive<PlotProperty, (typeof PLOT_PROPERTIES)[number]>,
] = [true, true, true, true];
void exhaustive;

let cp: CoolProp;

beforeAll(async () => {
  cp = await loadCoolProp();
});

describe("module", () => {
  it("reports the CoolProp version", () => {
    expect(cp.version()).toMatch(/^8\./);
  });

  it("lists the curated catalog with aliases", () => {
    const water = cp.catalog().find((f) => f.name === "Water");
    expect(water?.aliases).toContain("H2O");
    expect(water?.molar_mass).toBeCloseTo(0.018015268, 9);
  });
});

describe("schema", () => {
  it("lists exactly the inputs, phases and properties in the TS types", () => {
    expect(cp.inputs().map((i) => i.name)).toEqual(INPUT_NAMES);
    expect(cp.phases().map((p) => p.name)).toEqual(PHASES);
    expect(cp.phases().find((p) => p.name === "two_phase")?.label).toBe("two-phase");
    expect(cp.properties().map((p) => p.name)).toEqual(PROPERTY_NAMES);
  });

  it("lists exactly the pairs StateInputs accepts", () => {
    expect(cp.pairs()).toEqual(INPUT_PAIRS);
  });

  it("describes units, bounds and nullability", () => {
    const quality = cp.inputs().find((i) => i.name === "quality")!;
    expect([quality.min, quality.max]).toEqual([0, 1]);
    const viscosity = cp.properties().find((p) => p.name === "viscosity")!;
    expect(viscosity).toMatchObject({ unit: "Pa·s", nullable: true, category: "transport" });
  });

  it("matches the keys of a solved state", () => {
    const s = cp.fluid("Water").state({ pressure: 101325, temperature: 298.15 });
    const keys = Object.keys(s).filter((k) => k !== "phase");
    expect(keys.sort()).toEqual([...PROPERTY_NAMES].sort());
  });
});

describe("diagrams", () => {
  it("lists every plot property and diagram", () => {
    expect(cp.plotProperties().map((p) => p.name)).toEqual(PLOT_PROPERTIES);
    const ids = cp.diagrams().map((d) => d.id);
    expect(ids).toEqual([
      "pressure_enthalpy",
      "temperature_entropy",
      "enthalpy_entropy",
      "pressure_specific_volume",
      "temperature_specific_volume",
      "pressure_temperature",
    ]);
    const ph = cp.diagrams().find((d) => d.id === "pressure_enthalpy")!;
    expect(ph.y).toEqual({ property: "pressure", scale: "log" });
    const pt = cp.diagrams().find((d) => d.id === "pressure_temperature")!;
    expect(pt.y).toEqual({ property: "pressure", scale: "linear" });
    expect(ph.isolines).toContain("temperature");
    expect(ph.isolines).not.toContain("pressure");
  });

  it("builds a diagram projected onto its axes", () => {
    const d = cp.fluid("Water").diagram({
      diagram: "pressure_enthalpy",
      points: 40,
      isolines: [
        { kind: "temperature", count: 3 },
        { kind: "quality", values: [0.5] },
      ],
    });
    expect(d.x.property).toBe("enthalpy");
    expect(d.y.scale).toBe("log");
    expect(d.y.range![0]).toBeLessThan(d.y.range![1]);
    expect(d.dome.liquid.x).toHaveLength(d.dome.liquid.y.length);
    expect(d.isolines).toHaveLength(4);
    expect(d.isolines[3]).toMatchObject({ kind: "quality", value: 0.5 });
    expect(d.isolines[3].y.every((p) => typeof p === "number")).toBe(true);
  });

  it("suggests isoline values that are round in the display unit", () => {
    const d = cp.fluid("Water").diagram({
      diagram: "enthalpy_entropy",
      points: 10,
      isolines: [{ kind: "temperature", count: 7, unit: { scale: 1, offset: -273.15 } }],
    });
    const celsius = d.isolines.map((iso) => iso.value - 273.15);
    [50, 100, 150, 200, 250, 300, 350].forEach((c, i) => expect(celsius[i]).toBeCloseTo(c, 9));
  });

  it("traces the dome at the requested resolution, within bounds", () => {
    const water = cp.fluid("Water");
    const fine = water.diagram({ diagram: "temperature_entropy", dome_points: 200 });
    expect(fine.dome.vapor.x.length).toBeGreaterThan(180);
    expect(() => water.diagram({ diagram: "temperature_entropy", dome_points: 501 })).toThrowError(
      expect.objectContaining({ kind: "invalid_input" }),
    );
    expect(() =>
      water.diagram({ diagram: "temperature_entropy", isolines: [{ kind: "pressure", count: 31 }] }),
    ).toThrowError(expect.objectContaining({ kind: "invalid_input" }));
    // 20 isolines × 300 points exceeds the 5000-state budget.
    expect(() =>
      water.diagram({
        diagram: "temperature_entropy",
        points: 300,
        isolines: [{ kind: "pressure", count: 20 }],
      }),
    ).toThrowError(expect.objectContaining({ kind: "invalid_input" }));
  });

  it("marks unsolvable points as null breaks", () => {
    // This isentrope leaves the domain partway.
    const [iso] = cp.fluid("Water").diagram({
      diagram: "pressure_enthalpy",
      points: 40,
      isolines: [{ kind: "entropy", values: [12668] }],
    }).isolines;
    expect(iso.x.some((v) => v === null)).toBe(true);
    expect(iso.x.some((v) => typeof v === "number")).toBe(true);
  });

  it("rejects unknown diagrams and axis isolines", () => {
    const water = cp.fluid("Water");
    expect(() => water.diagram({ diagram: "nope" })).toThrowError(
      expect.objectContaining({ kind: "invalid_input" }),
    );
    expect(() =>
      water.diagram({ diagram: "pressure_enthalpy", isolines: [{ kind: "pressure" }] }),
    ).toThrowError(expect.objectContaining({ kind: "invalid_input" }));
  });
});

describe("fluid", () => {
  it("opens by alias and exposes data and the EOS critical point", () => {
    const water = cp.fluid("H2O");
    expect(water.name).toBe("Water");
    expect(water.critical.temperature).toBeCloseTo(647.096, 3);
    expect(water.data.t_triple).toBeCloseTo(273.16, 6);
  });

  it("rejects unknown fluids", () => {
    expect(() => cp.fluid("Unobtainium")).toThrowError(
      expect.objectContaining({ name: "CoolPropError", kind: "unknown_fluid" }),
    );
  });
});

describe("state", () => {
  it("solves a liquid from pressure and temperature", () => {
    const s = cp.fluid("Water").state({ pressure: 101325, temperature: 298.15 });
    expect(s.phase).toBe("liquid");
    expect(s.quality).toBeNull();
    expect(s.enthalpy).toBeCloseTo(104920.1, 0);
    expect(s.cp).toBeGreaterThan(4000);
  });

  it("round-trips through another input pair", () => {
    const water = cp.fluid("Water");
    const a = water.state({ pressure: 101325, quality: 0.5 });
    const b = water.state({ enthalpy: a.enthalpy, entropy: a.entropy });
    expect(b.pressure).toBeCloseTo(101325, 0);
    expect(b.quality).toBeCloseTo(0.5, 6);
  });

  it("classifies errors", () => {
    const water = cp.fluid("Water");
    const kindOf = (fn: () => unknown) => {
      try {
        fn();
      } catch (e) {
        return (e as CoolPropError).kind;
      }
      return "no error";
    };
    expect(kindOf(() => water.state({ pressure: 101325, temperature: -10 }))).toBe("coolprop");
    // Bypass the type check to reach the runtime validation.
    expect(kindOf(() => water.state({ pressure: 1 } as never))).toBe("invalid_input");
  });

  it("solves a state the same whatever was solved before", () => {
    // A density–quality flash once left the session unable to solve
    // pressure–temperature states near 1 atm.
    const water = cp.fluid("Water");
    const vapor = { pressure: 101000, temperature: 373.15 } as const;
    const before = water.state(vapor);
    water.state({ density: before.density, quality: 0.1 });
    expect(water.state(vapor).density).toBeCloseTo(before.density, 10);
  });

  it("flags pseudo-pure mixtures, which refuse density with quality", () => {
    expect(cp.fluid("R410A").data.pseudo_pure).toBe(true);
    expect(cp.fluid("Water").data.pseudo_pure).toBe(false);
    const r410a = cp.fluid("R410A");
    const wet = r410a.state({ pressure: 1.5e6, quality: 0.4 });
    expect(() => r410a.state({ density: wet.density, quality: 0.4 })).toThrowError(
      expect.objectContaining({ kind: "invalid_input" }),
    );
  });

  it("leaves single-phase properties undefined inside the dome", () => {
    const wet = cp.fluid("Water").state({ pressure: 101325, quality: 0.5 });
    expect([wet.cp, wet.cv, wet.viscosity, wet.conductivity, wet.speed_of_sound]).toEqual([
      null, null, null, null, null,
    ]);
    const saturated = cp.fluid("Water").state({ pressure: 101325, quality: 0 });
    expect(saturated.cp).toBeGreaterThan(4000);
  });

  it("solves batches point by point", () => {
    const [liquid, bad, vapor] = cp.fluid("Water").states([
      { pressure: 101325, quality: 0 },
      { pressure: 101325, temperature: -10 },
      { pressure: 101325, quality: 1 },
    ]);
    expect((liquid as { quality: number }).quality).toBe(0);
    expect(bad).toBeInstanceOf(CoolPropError);
    expect((bad as CoolPropError).kind).toBe("coolprop");
    expect((vapor as { quality: number }).quality).toBe(1);
  });

  it("does not leak module memory across many calls", async () => {
    // A dedicated instance whose Emscripten module we can inspect.
    let module: CoolPropModule & { HEAPU8: Uint8Array };
    const own = await loadCoolProp({
      moduleFactory: async (opts) => (module = await createCoolPropModule(opts)),
    });
    const water = own.fluid("Water");
    const call = (i: number) => water.state({ pressure: 101325, temperature: 280 + (i % 50) });
    for (let i = 0; i < 100; i++) call(i); // warm up the allocator
    const before = module!.HEAPU8.buffer.byteLength;
    // Each response is ~0.5 kB of module memory. If any leaked, 50k calls
    // (~24 MB, more than the whole initial ~18 MB heap) would force it to grow.
    for (let i = 0; i < 50000; i++) call(i);
    expect(module!.HEAPU8.buffer.byteLength).toBe(before);
  });
});

/** Compile-time only: never called. `tsc --noEmit` fails if any line type-checks. */
export function typeChecks(cp: CoolProp) {
  const water = cp.fluid("Water");
  // @ts-expect-error: one input is not enough.
  water.state({ pressure: 101325 });
  // @ts-expect-error: three inputs are too many.
  water.state({ pressure: 101325, temperature: 300, density: 1 });
  // @ts-expect-error: (quality, internal_energy) is not a supported pair.
  water.state({ quality: 0.5, internal_energy: 2e5 });
  // @ts-expect-error: short names are not part of the contract.
  water.state({ P: 101325, T: 300 });
}
